import { describe, expect, it } from "vitest";
import {
  isMockProvider,
  MOCK_MODE_POINTS,
  MOCK_PROVIDER_WARNING,
  PROVIDER_OPTIONS,
  RULE_BASED_MODE_DESCRIPTION,
} from "@/lib/mock-provider-disclosure";

describe("mock provider disclosure", () => {
  it("uses truthful MockProvider warning copy", () => {
    expect(MOCK_PROVIDER_WARNING).toContain("generated by MockProvider");
    expect(MOCK_PROVIDER_WARNING).toContain("fixed demonstration");
    expect(MOCK_PROVIDER_WARNING).toContain("does not reflect your source text");
    expect(MOCK_PROVIDER_WARNING).toContain("Use Rule-based, OpenAI, Gemini, or Ollama");
  });

  it("explains mock mode limitations on the extraction page", () => {
    expect(MOCK_MODE_POINTS).toContain("Mock mode is a fixed demo provider.");
    expect(MOCK_MODE_POINTS).toContain("Mock mode does not analyze the pasted text.");
    expect(MOCK_MODE_POINTS).toContain("It is useful for testing the pipeline only.");
  });

  it("labels provider choices without implying mock is real AI", () => {
    const auto = PROVIDER_OPTIONS.find((option) => option.value === "auto");
    const ruleBased = PROVIDER_OPTIONS.find((option) => option.value === "rule_based");
    const mock = PROVIDER_OPTIONS.find((option) => option.value === "mock");

    expect(auto?.label).toBe("Auto");
    expect(auto?.description).toContain("Rule-based local");
    expect(ruleBased?.label).toBe("Rule-based local");
    expect(ruleBased?.description).toContain("no API key needed");
    expect(mock?.label).toBe("Mock demo");
    expect(mock?.description).toBe("Mock demo: fixed chemostat fixture.");
  });

  it("orders default provider choices for the selector", () => {
    expect(PROVIDER_OPTIONS.map((option) => option.value)).toEqual([
      "auto",
      "rule_based",
      "mock",
      "openai",
      "gemini",
      "ollama",
    ]);
  });

  it("explains rule-based local mode", () => {
    expect(RULE_BASED_MODE_DESCRIPTION).toContain("free");
    expect(RULE_BASED_MODE_DESCRIPTION).toContain("without API keys");
    expect(RULE_BASED_MODE_DESCRIPTION).toContain("deterministic patterns");
  });

  it("only treats exact mock providerUsed values as mock", () => {
    expect(isMockProvider("mock")).toBe(true);
    expect(isMockProvider("openai")).toBe(false);
    expect(isMockProvider(null)).toBe(false);
  });
});
