// Extraction engine.
//
// Provider abstraction:
//   Today only the deterministic `MockProvider` exists. Real providers
//   (OpenAI, Gemini) will implement the same `ExtractionProvider` interface
//   and be selected at runtime by `getActiveProvider()` based on env vars.
//   Never hardcode keys.
//
// Validation contract:
//   `runExtraction()` is the single public entry point. It validates the
//   input text, calls the active provider, and re-validates the provider's
//   output against `ExtractionResultSchema`. Callers receive either a fully
//   validated `ExtractionResult` or one of two typed errors.
//
// Database mapping:
//   `mapExtractionToDb()` is a pure function that converts an
//   `ExtractionResult` into the row shapes the routes layer inserts. The
//   richer fields that don't have a column (e.g. equation confidence,
//   per-assumption confidence, model_card.inputs/outputs) are folded into
//   adjacent text fields where useful and otherwise dropped — without
//   changing the DB schema.

import {
  ExtractionResultSchema,
  type ExtractionResult,
  type ExtractedModelCardMeta,
} from "./extraction-schema";

// ---------- Public errors ----------

/** Bad input from the user (empty / too short). 400 territory. */
export class ExtractionInputError extends Error {
  readonly status = 400 as const;
  constructor(message: string) {
    super(message);
    this.name = "ExtractionInputError";
  }
}

/** Provider failed or returned malformed output. 502 territory. */
export class ExtractionProviderError extends Error {
  readonly status = 502 as const;
  constructor(
    message: string,
    readonly providerName: string,
  ) {
    super(message);
    this.name = "ExtractionProviderError";
  }
}

// ---------- Provider interface ----------

export type ProviderName = "mock" | "openai" | "gemini";

export interface ExtractionProvider {
  readonly name: ProviderName;
  /**
   * Producer of an extraction. Implementations may return any shape; the
   * orchestrator re-validates against `ExtractionResultSchema` so providers
   * never bypass validation.
   */
  extract(sourceText: string): Promise<unknown>;
}

// ---------- Mock provider ----------

const TITLE_MAX = 90;

function deriveTitle(sourceText: string): string {
  const firstLine = sourceText
    .split(/\r?\n/)
    .map((l) => l.trim())
    .find((l) => l.length > 0);
  if (!firstLine) return "Untitled extraction";
  return firstLine.length > TITLE_MAX
    ? firstLine.slice(0, TITLE_MAX - 3) + "..."
    : firstLine;
}

class MockProvider implements ExtractionProvider {
  readonly name = "mock" as const;

  async extract(sourceText: string): Promise<ExtractionResult> {
    const title = deriveTitle(sourceText);
    return {
      paper_title_or_topic: title,
      system_type: "Generic dynamic system (mock)",
      process_description:
        "Mock extraction generated without a real AI provider configured. " +
        "Demonstrates the canonical structure: a model card with state " +
        "variables, parameters, equations, assumptions, and limitations.",
      state_variables: [
        {
          symbol: "x",
          name: "Lumped state",
          meaning: "Single lumped state variable for the mock system.",
          unit: "—",
          role: "state",
          source_context:
            "(mock) Single state generated by the mock extractor.",
          confidence: "low",
        },
        {
          symbol: "t",
          name: "Time",
          meaning: "Independent variable of integration.",
          unit: "s",
          role: "input",
          source_context: "(mock) Independent variable.",
          confidence: "high",
        },
      ],
      parameters: [
        {
          symbol: "k",
          name: "Rate constant",
          value: "0.1",
          unit: "1/s",
          source_context:
            "(mock) Default rate constant — replace with real value.",
          confidence: "low",
        },
      ],
      equations: [
        {
          label: "(1)",
          equation_latex: "\\frac{dx}{dt} = -k\\, x",
          equation_plaintext: "dx/dt = -k * x",
          meaning: "First-order decay of the lumped state.",
          variables_involved: ["x", "t", "k"],
          source_context: "(mock) Assumed first-order kinetics.",
          confidence: "low",
        },
      ],
      assumptions: [
        {
          assumption: "Lumped, well-mixed system with no spatial variation.",
          source_context: "(mock)",
          confidence: "medium",
        },
        {
          assumption: "Constant temperature.",
          source_context: "(mock)",
          confidence: "medium",
        },
      ],
      limitations: [
        {
          limitation:
            "Mock extraction — configure OPENAI_API_KEY or GEMINI_API_KEY for real results in a future milestone.",
          source_context: "(mock)",
          confidence: "high",
        },
      ],
      model_card: {
        short_summary: `Mock extraction for "${title}".`,
        model_type: "Lumped ODE",
        inputs: ["t"],
        outputs: ["x"],
        control_variables: [],
        missing_information: [
          "Real source quotes (mock provider)",
          "Numeric parameter values from the source paper",
        ],
        can_generate_ode_template: true,
      },
    };
  }
}

// ---------- Provider factory ----------

/**
 * Select the active extraction provider. Today: always mock. Future
 * milestones will inspect env vars (never hardcoded keys) and instantiate
 * an OpenAI or Gemini provider when configured.
 */
export function getActiveProvider(): ExtractionProvider {
  // if (process.env["OPENAI_API_KEY"]) return new OpenAIProvider();
  // if (process.env["GEMINI_API_KEY"]) return new GeminiProvider();
  return new MockProvider();
}

// ---------- Public entry point ----------

export const MIN_SOURCE_CHARS = 30;

export async function runExtraction(sourceText: string): Promise<{
  result: ExtractionResult;
  providerName: ProviderName;
}> {
  const trimmed = sourceText.trim();
  if (trimmed.length === 0) {
    throw new ExtractionInputError("Source text is empty.");
  }
  if (trimmed.length < MIN_SOURCE_CHARS) {
    throw new ExtractionInputError(
      `Source text is too short to extract a model (need at least ${MIN_SOURCE_CHARS} characters, got ${trimmed.length}).`,
    );
  }

  const provider = getActiveProvider();

  let raw: unknown;
  try {
    raw = await provider.extract(trimmed);
  } catch (err) {
    throw new ExtractionProviderError(
      `Provider threw: ${err instanceof Error ? err.message : String(err)}`,
      provider.name,
    );
  }

  const parsed = ExtractionResultSchema.safeParse(raw);
  if (!parsed.success) {
    throw new ExtractionProviderError(
      `Provider returned malformed extraction JSON: ${parsed.error.message}`,
      provider.name,
    );
  }

  return { result: parsed.data, providerName: provider.name };
}

// ---------- DB mapping ----------

export type DbExtractionRow = {
  modelCardTitle: string;
  domain: string;
  systemDescription: string;
  problemStatement: string;
  odeTemplate: string;
};

export type DbEquationRow = {
  ordinal: number;
  latex: string;
  description: string;
  sourceQuote: string;
};

export type DbVariableRow = {
  ordinal: number;
  symbol: string;
  name: string;
  unit: string;
  role: "state" | "input" | "output";
  sourceQuote: string;
};

export type DbParameterRow = {
  ordinal: number;
  symbol: string;
  value: number;
  unit: string;
  confidence: "high" | "medium" | "low";
  sourceQuote: string;
};

export type DbAssumptionRow = {
  ordinal: number;
  kind: "assumption" | "limitation";
  text: string;
};

export type MappedExtraction = {
  extraction: DbExtractionRow;
  equations: DbEquationRow[];
  variables: DbVariableRow[];
  parameters: DbParameterRow[];
  assumptions: DbAssumptionRow[];
};

const NUMBER_RE = /-?\d+(?:\.\d+)?(?:[eE][-+]?\d+)?/;

function parseNumeric(value: string): { num: number; ok: boolean } {
  const trimmed = value.trim();
  const direct = Number(trimmed);
  if (Number.isFinite(direct)) return { num: direct, ok: true };
  const m = trimmed.match(NUMBER_RE);
  if (m) {
    const n = Number(m[0]);
    if (Number.isFinite(n)) return { num: n, ok: true };
  }
  return { num: 0, ok: false };
}

/** Reduce the rich provider-side role enum to the simplified DB enum. */
function downgradeRole(role: string): "state" | "input" | "output" {
  if (role === "state" || role === "input" || role === "output") return role;
  // "parameter" and "control" map to "input" for storage.
  return "input";
}

function buildSystemDescription(r: ExtractionResult): string {
  const parts: string[] = [];
  if (r.process_description) parts.push(r.process_description);
  if (r.model_card.short_summary)
    parts.push(`\n\nSummary: ${r.model_card.short_summary}`);
  if (r.model_card.model_type)
    parts.push(`\nModel type: ${r.model_card.model_type}`);
  return parts.join("");
}

function buildProblemStatement(card: ExtractedModelCardMeta): string {
  const parts: string[] = [];
  if (card.outputs.length) parts.push(`Predict: ${card.outputs.join(", ")}.`);
  if (card.inputs.length)
    parts.push(`Given inputs: ${card.inputs.join(", ")}.`);
  if (card.control_variables.length)
    parts.push(`Control variables: ${card.control_variables.join(", ")}.`);
  if (card.missing_information.length)
    parts.push(
      `Missing information: ${card.missing_information.join("; ")}.`,
    );
  return parts.join(" ") || "—";
}

function buildOdeTemplate(r: ExtractionResult): string {
  if (!r.model_card.can_generate_ode_template) {
    return "# ODE template not available — provider reported can_generate_ode_template=false.\n";
  }
  const stateSyms = r.state_variables
    .filter((v) => v.role === "state")
    .map((v) => v.symbol);
  const paramAssignments = r.parameters
    .map((p) => {
      const { num, ok } = parseNumeric(p.value);
      const note = ok ? "" : `  # NOTE: could not parse "${p.value}"`;
      return `    "${p.symbol}": ${ok ? num : 0.0},  # ${p.unit || "—"}${note}`;
    })
    .join("\n");
  const initial = stateSyms.length
    ? stateSyms.map(() => "1.0").join(", ")
    : "1.0";

  return `# Generated ODE template — review and fill in any placeholders.
# State variables: ${stateSyms.join(", ") || "(none extracted)"}
# Solver: scipy.integrate.solve_ivp (RK45)

import numpy as np
from scipy.integrate import solve_ivp


PARAMS = {
${paramAssignments || "    # (no parameters extracted)"}
}


def rhs(t, y, p):
    """Right-hand side of the ODE system. Edit to match the extracted equations."""
    dydt = np.zeros_like(y)
    # TODO: implement equations using ${stateSyms.join(", ") || "the extracted states"}
    return dydt


def simulate(y0, t_span=(0.0, 100.0), n_points=200):
    sol = solve_ivp(
        fun=lambda t, y: rhs(t, y, PARAMS),
        t_span=t_span,
        y0=y0,
        t_eval=np.linspace(t_span[0], t_span[1], n_points),
        method="RK45",
    )
    return sol


if __name__ == "__main__":
    sol = simulate(y0=[${initial}])
    print(sol.t[:5], sol.y[:, :5])
`;
}

function formatVariableName(name: string, meaning: string): string {
  const n = name.trim();
  const m = meaning.trim();
  if (!m || m === n) return n;
  if (!n) return m;
  return `${n} — ${m}`;
}

function formatEquationDescription(
  label: string,
  meaning: string,
  plaintext: string,
): string {
  const parts: string[] = [];
  if (label) parts.push(`[${label}]`);
  if (meaning) parts.push(meaning);
  if (plaintext && plaintext !== meaning) parts.push(`(${plaintext})`);
  return parts.join(" ");
}

export function mapExtractionToDb(r: ExtractionResult): MappedExtraction {
  const extraction: DbExtractionRow = {
    modelCardTitle: r.paper_title_or_topic,
    domain: r.system_type,
    systemDescription: buildSystemDescription(r),
    problemStatement: buildProblemStatement(r.model_card),
    odeTemplate: buildOdeTemplate(r),
  };

  const equations: DbEquationRow[] = r.equations.map((eq, i) => ({
    ordinal: i,
    latex: eq.equation_latex,
    description: formatEquationDescription(
      eq.label,
      eq.meaning,
      eq.equation_plaintext,
    ),
    sourceQuote: eq.source_context,
  }));

  const variables: DbVariableRow[] = r.state_variables.map((v, i) => ({
    ordinal: i,
    symbol: v.symbol,
    name: formatVariableName(v.name, v.meaning),
    unit: v.unit,
    role: downgradeRole(v.role),
    sourceQuote: v.source_context,
  }));

  const parameters: DbParameterRow[] = r.parameters.map((p, i) => {
    const { num, ok } = parseNumeric(p.value);
    return {
      ordinal: i,
      symbol: p.symbol,
      value: num,
      unit: p.unit,
      // If we couldn't parse the value, downgrade confidence so the UI
      // surfaces the uncertainty regardless of what the provider claimed.
      confidence: ok ? p.confidence : "low",
      sourceQuote:
        (p.name ? `${p.name}. ` : "") +
        (ok ? "" : `(value "${p.value}" could not be parsed numerically) `) +
        p.source_context,
    };
  });

  const assumptions: DbAssumptionRow[] = [
    ...r.assumptions.map((a, i) => ({
      ordinal: i,
      kind: "assumption" as const,
      text: a.assumption,
    })),
    ...r.limitations.map((l, i) => ({
      ordinal: i,
      kind: "limitation" as const,
      text: l.limitation,
    })),
  ];

  return { extraction, equations, variables, parameters, assumptions };
}
