export type ProviderChoice =
  | "auto"
  | "rule_based"
  | "mock"
  | "openai"
  | "gemini"
  | "groq"
  | "ollama";

export const MOCK_PROVIDER_WARNING =
  "Demo mode — this model card was generated by MockProvider and does not reflect your source text. It is a fixed demonstration. Use Rule-based, OpenAI, Gemini, Groq, or Ollama for real extraction.";

export const GROQ_PROVIDER_NOTICE =
  "Groq cloud AI was used for paper understanding.";

export const GROQ_RULE_BASED_FALLBACK_WARNING =
  "Groq was unavailable or budget-limited. RuleBased fallback was used. This is deterministic local extraction, not full-paper AI understanding.";

export const RULE_BASED_DIRECT_WARNING =
  "Rule-based local extraction was used (selected directly). This is deterministic pattern matching, not full-paper AI understanding. Equations and parameters not matching the built-in patterns will be missed.";

export const CHEME_BRAIN_DEMO_SOURCE_WARNING =
  "This ChemE Brain audit is based on a Mock (demonstration) extraction, not your source text. The verdict, missing-information list, and recommendations are illustrative only.";

export const CHEME_BRAIN_RULE_BASED_SOURCE_WARNING =
  "This ChemE Brain audit is based on a Rule-based (deterministic, non-AI) extraction. Items the rule engine could not match will appear as missing even if your paper contains them.";

export const CHEME_BRAIN_V1_SCOPE_NOTICE =
  "ChemE Brain v1 is currently strongest for bioprocess/bioreactor-style models such as Monod chemostat, batch culture, fed-batch, gas-liquid, enzyme kinetics, photobioreactors, and oxygen-balanced mixotrophy. Other ChemE domains may be classified as unsupported or require manual review.";

export function isRuleBasedProvider(providerUsed: string | null | undefined): boolean {
  return providerUsed === "rule_based";
}

export const MOCK_MODE_POINTS = [
  "Mock mode is a fixed demo provider.",
  "Mock mode does not analyze the pasted text.",
  "It is useful for testing the pipeline only.",
] as const;

export const RULE_BASED_MODE_DESCRIPTION =
  "Rule-based local mode is free and works without API keys. It extracts obvious equations, parameters, and units using deterministic patterns.";

export const PROVIDER_OPTIONS: {
  value: ProviderChoice;
  label: string;
  description: string;
}[] = [
  {
    value: "auto",
    label: "Auto",
    description: "Uses configured providers first, then Rule-based local; Mock is explicit demo only",
  },
  {
    value: "rule_based",
    label: "Rule-based local",
    description: "Free deterministic extraction; no API key needed",
  },
  {
    value: "mock",
    label: "Mock demo",
    description: "Mock demo: fixed chemostat fixture.",
  },
  {
    value: "openai",
    label: "OpenAI (GPT-4o)",
    description: "Requires OPENAI_API_KEY",
  },
  {
    value: "gemini",
    label: "Gemini 1.5 Flash",
    description: "Requires GEMINI_API_KEY",
  },
  {
    value: "groq",
    label: "Groq cloud AI",
    description: "Server-side GROQ_API_KEY; conservative free-tier limits",
  },
  {
    value: "ollama",
    label: "Ollama (local free)",
    description: "Requires local Ollama server",
  },
];

export function isMockProvider(providerUsed: string | null | undefined): boolean {
  return providerUsed === "mock";
}
