export type ProviderChoice =
  | "auto"
  | "rule_based"
  | "mock"
  | "openai"
  | "gemini"
  | "ollama";

export const MOCK_PROVIDER_WARNING =
  "Demo mode: this model card was generated by MockProvider. It is a fixed demonstration and may not reflect your source text. Configure OpenAI, Gemini, or a local provider to enable real extraction.";

export const MOCK_MODE_POINTS = [
  "Mock mode is a fixed demo provider.",
  "Mock mode does not analyze the pasted text.",
  "It is useful for testing the pipeline only.",
] as const;

export const RULE_BASED_MODE_DESCRIPTION =
  "Rule-based local mode is free and works without API keys. It extracts obvious equations, parameters, and units using deterministic patterns.";

export const PROVIDER_OPTIONS: {
  value: ProviderChoice;
  label: string;
  description: string;
}[] = [
  {
    value: "auto",
    label: "Auto",
    description: "Uses configured providers first, then Rule-based local, then Mock demo",
  },
  {
    value: "rule_based",
    label: "Rule-based local",
    description: "Free deterministic extraction; no API key needed",
  },
  {
    value: "mock",
    label: "Mock demo",
    description: "Mock demo: fixed chemostat fixture.",
  },
  {
    value: "openai",
    label: "OpenAI (GPT-4o)",
    description: "Requires OPENAI_API_KEY",
  },
  {
    value: "gemini",
    label: "Gemini 1.5 Flash",
    description: "Requires GEMINI_API_KEY",
  },
  {
    value: "ollama",
    label: "Ollama (local free)",
    description: "Requires local Ollama server",
  },
];

export function isMockProvider(providerUsed: string | null | undefined): boolean {
  return providerUsed === "mock";
}
