/**
 * Jupyter Notebook Generator — M25
 *
 * Pure TypeScript, client-side only. Produces a valid .ipynb JSON string from
 * the same PythonGeneratorInput used by python-generator.ts.
 *
 * Design contract:
 *  - Generates exactly 14 cells (7 Markdown + 6 Code + 1 Markdown notes)
 *  - Reuses the already-computed pythonCode to avoid duplicating generation logic
 *  - Splits the Python code into sections using the DIVIDER markers
 *  - Honest: scaffold-only cells are clearly marked with TODO comments
 *  - Does NOT remove or replace the existing .py download — this is additive
 */

import type { PythonGeneratorInput } from "./python-generator";
import type { RawExtraction } from "./reproducibility";
import { getParameterDisplayValue } from "./parameter-values";

// ─── Public input type ─────────────────────────────────────────────────────────

export interface NotebookGeneratorInput extends PythonGeneratorInput {
  /** Already-computed Python code from generatePythonOdeTemplate(). */
  pythonCode: string;
}

// ─── Internal notebook types ────────────────────────────────────────────────────

interface MarkdownCell {
  cell_type: "markdown";
  id: string;
  metadata: object;
  source: string;
}

interface CodeCell {
  cell_type: "code";
  execution_count: null;
  id: string;
  metadata: object;
  outputs: never[];
  source: string;
}

type NotebookCell = MarkdownCell | CodeCell;

// ─── Helpers ────────────────────────────────────────────────────────────────────

function mdCell(id: string, source: string): MarkdownCell {
  return { cell_type: "markdown", id, metadata: {}, source };
}

function codeCell(id: string, source: string): CodeCell {
  return { cell_type: "code", execution_count: null, id, metadata: {}, outputs: [], source };
}

function cellId(n: number): string {
  return `chemengai-${String(n).padStart(2, "0")}`;
}

function safe(v: unknown): string {
  return v == null ? "" : String(v).trim();
}

/** Escape a string for inline Markdown (backticks, pipes, etc.). */
function mdEsc(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/`/g, "'");
}

/**
 * Split Python code into named sections using the DIVIDER pattern from
 * python-generator.ts: `# ={76}\n# SECTION_NAME\n# ={76}`.
 */
function parsePythonSections(code: string): Record<string, string> {
  const d = "# " + "=".repeat(76);
  const escaped = d.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
  // Match section headers, possibly preceded by a newline
  const re = new RegExp(`(?:^|\\n)${escaped}\\n# ([^\\n]+)\\n${escaped}`, "g");

  const parts: Array<{ name: string; start: number; headerEnd: number }> = [];
  let m: RegExpExecArray | null;
  while ((m = re.exec(code)) !== null) {
    parts.push({
      name: m[1].trim(),
      start: m.index,
      headerEnd: m.index + m[0].length,
    });
  }

  const sections: Record<string, string> = {};
  for (let i = 0; i < parts.length; i++) {
    const contentStart = parts[i].headerEnd;
    const contentEnd =
      i + 1 < parts.length ? parts[i + 1].start : code.length;
    sections[parts[i].name] = code.slice(contentStart, contentEnd).trim();
  }
  return sections;
}

// ─── Cell generators (Markdown) ────────────────────────────────────────────────

function makeTitleCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { title, projectName, providerUsed, systemType, systemDescription, raw } = input;
  const date = new Date().toISOString().slice(0, 10);
  const mc = (raw as RawExtraction | null)?.model_card;

  const lines: string[] = [
    `# ${title}`,
    "",
    `| Field | Value |`,
    `|-------|-------|`,
    `| **Project** | ${mdEsc(projectName)} |`,
    `| **Provider** | ${mdEsc(providerUsed)} |`,
    `| **System type** | ${mdEsc(safe(systemType) || "unspecified")} |`,
    `| **Generated** | ${date} |`,
    "",
    "---",
    "",
    "## Model Summary",
    "",
  ];

  if (mc?.short_summary) {
    lines.push(mc.short_summary, "");
  }
  if (systemDescription) {
    lines.push("**System description:**", "", systemDescription, "");
  }
  if (mc?.model_type) {
    lines.push(`**Model type:** ${mc.model_type}`, "");
  }
  const mcInputs = mc?.inputs ?? [];
  const mcOutputs = mc?.outputs ?? [];
  const mcControl = mc?.control_variables ?? [];
  if (mcInputs.length) lines.push(`**Inputs:** ${mcInputs.join(", ")}`, "");
  if (mcOutputs.length) lines.push(`**Outputs:** ${mcOutputs.join(", ")}`, "");
  if (mcControl.length) lines.push(`**Control variables:** ${mcControl.join(", ")}`, "");

  lines.push(
    "> ⚠️ This notebook was auto-generated by ChemAI Model Compiler.",
    "> Review all TODO cells before running.",
    "> Do not treat scaffold code as a verified simulation without expert review.",
  );

  return mdCell(id, lines.join("\n"));
}

function makeVariablesCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { variables } = input;
  const lines: string[] = [
    "## 📊 State Variables",
    "",
    "| Symbol | Name | Unit | Role | Confidence |",
    "|--------|------|------|------|------------|",
  ];
  if (variables.length === 0) {
    lines.push("| — | *(none extracted)* | — | — | — |");
  } else {
    for (const v of variables) {
      lines.push(
        `| \`${mdEsc(v.symbol)}\` | ${mdEsc(safe(v.name))} | ${mdEsc(safe(v.unit) || "—")} | ${v.role} | — |`,
      );
    }
  }
  return mdCell(id, lines.join("\n"));
}

function makeParametersCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { parameters } = input;
  const lines: string[] = [
    "## ⚙️ Parameters",
    "",
    "| Symbol | Value | Unit | Confidence |",
    "|--------|-------|------|------------|",
  ];
  if (parameters.length === 0) {
    lines.push("| — | *(none extracted)* | — | — |");
  } else {
    for (const p of parameters) {
      const val = getParameterDisplayValue(p);
      lines.push(
        `| \`${mdEsc(p.symbol)}\` | ${val} | ${mdEsc(safe(p.unit) || "—")} | ${p.confidence} |`,
      );
    }
  }
  return mdCell(id, lines.join("\n"));
}

function makeEquationsCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { equations, raw } = input;
  const rawEqs = (raw as RawExtraction | null)?.equations ?? [];
  const lines: string[] = ["## 📐 Governing Equations", ""];

  if (rawEqs.length === 0 && equations.length === 0) {
    lines.push("*(No equations were extracted.)*");
    return mdCell(id, lines.join("\n"));
  }

  if (rawEqs.length > 0) {
    for (let i = 0; i < rawEqs.length; i++) {
      const eq = rawEqs[i];
      const label = safe(eq.label) || `Equation ${i + 1}`;
      lines.push(`### ${i + 1}. ${label}`, "");
      if (eq.equation_latex) {
        lines.push(`$$${eq.equation_latex}$$`, "");
      }
      if (eq.equation_plaintext && eq.equation_plaintext !== eq.equation_latex) {
        lines.push(`**Plain text:** \`${eq.equation_plaintext}\``, "");
      }
      if (eq.meaning) {
        lines.push(`**Meaning:** ${eq.meaning}`, "");
      }
      const syms = (eq.variables_involved ?? []).filter(Boolean);
      if (syms.length) {
        lines.push(`**Symbols involved:** ${syms.map((s) => `\`${s}\``).join(", ")}`, "");
      }
      if (eq.source_context) {
        lines.push(`> ${eq.source_context}`, "");
      }
    }
  } else {
    for (let i = 0; i < equations.length; i++) {
      const eq = equations[i];
      lines.push(`### ${i + 1}. ${eq.description || "(no description)"}`, "");
      if (eq.latex) {
        lines.push(`$$${eq.latex}$$`, "");
      }
      if (eq.sourceQuote) {
        lines.push(`> ${eq.sourceQuote}`, "");
      }
    }
  }

  return mdCell(id, lines.join("\n"));
}

function makeMissingInfoCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { report, raw } = input;
  const criticals = report.missing_items.filter((m) => m.severity === "critical");
  const warnings = report.missing_items.filter((m) => m.severity === "warning");
  const rawMc = (raw as RawExtraction | null)?.model_card;
  const missingInfo = rawMc?.missing_information ?? [];

  const lines: string[] = ["## ⚠️ Missing Information Report", ""];

  if (criticals.length === 0 && warnings.length === 0 && missingInfo.length === 0) {
    lines.push("✅ No critical gaps detected.");
  } else {
    if (criticals.length > 0) {
      lines.push("### ❌ Critical — must resolve before simulation", "");
      for (const item of criticals) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
    if (warnings.length > 0) {
      lines.push("### ⚠️ Warnings — verify before trusting output", "");
      for (const item of warnings) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
    if (missingInfo.length > 0) {
      lines.push("### ℹ️ Model card — missing information noted by provider", "");
      for (const item of missingInfo) {
        lines.push(`- ${item}`);
      }
      lines.push("");
    }
  }

  if (report.recommended_next_steps.length > 0) {
    lines.push("### Recommended Next Steps", "");
    for (let i = 0; i < report.recommended_next_steps.length; i++) {
      lines.push(`${i + 1}. ${report.recommended_next_steps[i]}`);
    }
  }

  return mdCell(id, lines.join("\n"));
}

function makeReproducibilityCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { report } = input;
  const readinessLabel =
    report.simulation_readiness === "ready"
      ? "✅ Simulation Ready"
      : report.simulation_readiness === "partial"
        ? "⚠️ Partially Ready — review TODOs"
        : "❌ Not Ready — critical information missing";

  const lines: string[] = [
    "## 📈 Reproducibility Score",
    "",
    `**Overall score:** ${report.overall_score}/100`,
    "",
    `**Simulation readiness:** ${readinessLabel}`,
    "",
    "| Sub-score | Value |",
    "|-----------|-------|",
    `| Equations completeness | ${report.equations_completeness}/100 |`,
    `| Parameters completeness | ${report.parameters_completeness}/100 |`,
    `| Units completeness | ${report.units_completeness}/100 |`,
    `| Initial conditions | ${report.initial_conditions_completeness}/100 |`,
    `| Source traceability | ${report.source_traceability}/100 |`,
  ];

  if (report.main_blockers.length > 0) {
    lines.push("", "**Simulation blockers:**", "");
    for (const b of report.main_blockers) {
      lines.push(`- ${b}`);
    }
  }

  return mdCell(id, lines.join("\n"));
}

function makeUnitCheckCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { unitReport } = input;
  const statusLabel =
    unitReport.unit_check_status === "pass"
      ? "✅ Pass"
      : unitReport.unit_check_status === "warning"
        ? "⚠️ Warning"
        : "❌ Fail";

  const highWarns = unitReport.warnings.filter((w) => w.severity === "high");
  const medWarns = unitReport.warnings.filter((w) => w.severity === "medium");

  const lines: string[] = [
    "## 🔬 Unit Check Report",
    "",
    `**Status:** ${statusLabel}`,
    `**Issues:** ${highWarns.length} high · ${medWarns.length} medium`,
    "",
  ];

  if (highWarns.length > 0) {
    lines.push("### High-severity issues", "");
    for (const w of highWarns) {
      lines.push(`- **HIGH:** ${w.message}`);
      if (w.suggestion) lines.push(`  → ${w.suggestion}`);
    }
    lines.push("");
  }
  if (medWarns.length > 0) {
    lines.push("### Medium-severity issues", "");
    for (const w of medWarns) {
      lines.push(`- **MEDIUM:** ${w.message}`);
      if (w.suggestion) lines.push(`  → ${w.suggestion}`);
    }
    lines.push("");
  }
  if (highWarns.length === 0 && medWarns.length === 0) {
    lines.push("No unit issues detected by heuristic checker.");
  }

  return mdCell(id, lines.join("\n"));
}

function makeNotesCell(input: NotebookGeneratorInput, id: string): MarkdownCell {
  const { title, report, templateResult } = input;
  const tmplStatus = templateResult
    ? templateResult.status === "full"
      ? "full — all equations have runnable Python"
      : templateResult.status === "partial"
        ? `partial — ${templateResult.runnableCount}/${templateResult.totalEquations} equations runnable`
        : "scaffold only — equations need manual translation"
    : "not computed";

  const lines: string[] = [
    "## 📝 Notes & TODO",
    "",
    "### Before running this notebook",
    "",
    "- [ ] Review all `# TODO` comments in code cells",
    "- [ ] Verify parameter values against the original source document",
    "- [ ] Set realistic initial conditions for each state variable",
    "- [ ] Validate units are consistent throughout",
    "- [ ] Check reproducibility score above before trusting output",
    "",
    "### Runnable template status",
    "",
    `**Status:** ${tmplStatus}`,
    "",
    report.simulation_readiness !== "ready"
      ? [
          "### Simulation blockers",
          "",
          ...report.main_blockers.map((b) => `- ${b}`),
          "",
        ].join("\n")
      : "",
    "### Reference",
    "",
    `Generated from: **${title}**`,
    "",
    "Generated by [ChemAI Model Compiler](https://github.com/MehrzadJami/Test-Run).",
    "This is a scaffold — expert review is required before trusting simulation output.",
  ].filter(Boolean);

  return mdCell(id, lines.join("\n"));
}

// ─── Main entry point ───────────────────────────────────────────────────────────

/**
 * Generate a valid .ipynb JSON string from model card data.
 *
 * Returns 14 cells:
 *  1  Markdown — title + model summary
 *  2  Markdown — variables table
 *  3  Markdown — parameters table
 *  4  Markdown — equations in LaTeX
 *  5  Markdown — missing information report
 *  6  Markdown — reproducibility score
 *  7  Markdown — unit check report
 *  8  Code     — Python imports
 *  9  Code     — parameter dictionary
 *  10 Code     — initial conditions
 *  11 Code     — ODE function (scaffold or runnable)
 *  12 Code     — solve_ivp simulation
 *  13 Code     — plotting
 *  14 Markdown — notes/TODO
 */
export function generateJupyterNotebook(input: NotebookGeneratorInput): string {
  const { pythonCode } = input;
  const sections = parsePythonSections(pythonCode);

  // Section names from python-generator.ts
  const S_IMPORTS = "IMPORTS";
  const S_PARAMS = "PARAMETERS";
  const S_STATE = "STATE VARIABLES & INITIAL CONDITIONS";
  const S_EQ_REF = "EXTRACTED EQUATIONS  (shown as reference comments)";
  const S_ODE = "ODE FUNCTION";
  const S_SIM = "SIMULATION";
  const S_PLOT = "PLOTTING";

  // Combine equation reference comments with the ODE function into one cell
  const odeCellContent = [
    sections[S_EQ_REF] ?? "# (no equation reference comments)",
    "",
    sections[S_ODE] ?? "# TODO: implement ODE function",
  ]
    .join("\n")
    .trim();

  const cells: NotebookCell[] = [
    // ── Markdown descriptive cells ────────────────────────────────────────────
    makeTitleCell(input, cellId(1)),
    makeVariablesCell(input, cellId(2)),
    makeParametersCell(input, cellId(3)),
    makeEquationsCell(input, cellId(4)),
    makeMissingInfoCell(input, cellId(5)),
    makeReproducibilityCell(input, cellId(6)),
    makeUnitCheckCell(input, cellId(7)),
    // ── Code cells ────────────────────────────────────────────────────────────
    codeCell(
      cellId(8),
      sections[S_IMPORTS] ?? "import numpy as np\nfrom scipy.integrate import solve_ivp\nimport matplotlib.pyplot as plt",
    ),
    codeCell(
      cellId(9),
      sections[S_PARAMS] ?? "params = {}  # TODO: add parameters",
    ),
    codeCell(
      cellId(10),
      sections[S_STATE] ?? "y0 = []  # TODO: add initial conditions",
    ),
    codeCell(cellId(11), odeCellContent),
    codeCell(
      cellId(12),
      sections[S_SIM] ?? "# TODO: run simulation\n# sol = solve_ivp(ode_model, t_span, y0, args=(params,))",
    ),
    codeCell(
      cellId(13),
      sections[S_PLOT] ?? "# TODO: plot results",
    ),
    // ── Notes ─────────────────────────────────────────────────────────────────
    makeNotesCell(input, cellId(14)),
  ];

  const notebook = {
    nbformat: 4,
    nbformat_minor: 5,
    metadata: {
      kernelspec: {
        display_name: "Python 3",
        language: "python",
        name: "python3",
      },
      language_info: {
        codemirror_mode: { name: "ipython", version: 3 },
        file_extension: ".py",
        mimetype: "text/x-python",
        name: "python",
        nbconvert_exporter: "python",
        pygments_lexer: "ipython3",
        version: "3.10.0",
      },
    },
    cells,
  };

  return JSON.stringify(notebook, null, 2);
}
