/**
 * Reproducible Model Package Generator — M9
 *
 * Pure TypeScript, client-side only. Produces a Record<filename, content>
 * for every file in the model_package/ ZIP.
 *
 * Design contract:
 *  - Every generated file is honest: no hallucinated values or equations.
 *  - simulate.py is a safe scaffold (reuses python-generator output).
 *  - README explains what is extracted, what is missing, and how to run.
 *  - All scores, warnings, and gaps are embedded in the human-readable files.
 */

import type {
  AnalysisEquation,
  AnalysisVariable,
  AnalysisParameter,
  AnalysisAssumption,
  RawExtraction,
  ReproducibilityReport,
} from "./reproducibility";
import type { UnitCheckReport } from "./unit-checker";
import { generateJupyterNotebook } from "./notebook-generator";

// ─── Public input type ─────────────────────────────────────────────────────────

export interface ModelPackageInput {
  title: string;
  projectName: string;
  providerUsed: string;
  domain: string;
  systemType?: string | null;
  systemDescription?: string | null;
  problemStatement?: string | null;
  equations: AnalysisEquation[];
  variables: AnalysisVariable[];
  parameters: AnalysisParameter[];
  assumptionItems: AnalysisAssumption[];
  limitationItems: AnalysisAssumption[];
  raw: RawExtraction | null;
  report: ReproducibilityReport;
  unitReport: UnitCheckReport;
  pythonCode: string;
  review?: {
    status: "extracted" | "needs_review" | "reviewed" | "verified" | "rejected";
    reviewer_name?: string;
    review_notes?: string;
    reviewed_at?: string;
    verification_status?: string;
    issues_found?: string[];
  };
}

// ─── Helpers ──────────────────────────────────────────────────────────────────

function safe(v: unknown): string {
  return v == null ? "" : String(v).trim();
}

/** Escape a CSV cell: wrap in quotes and double any internal quotes. */
function csvCell(v: unknown): string {
  const s = safe(v);
  if (s.includes(",") || s.includes('"') || s.includes("\n")) {
    return `"${s.replace(/"/g, '""')}"`;
  }
  return s;
}

function csvRow(...cells: unknown[]): string {
  return cells.map(csvCell).join(",");
}

function hr(char = "-", len = 72): string {
  return char.repeat(len);
}

function readinessLabel(r: ReproducibilityReport["simulation_readiness"]): string {
  if (r === "ready") return "✅ Simulation Ready";
  if (r === "partial") return "⚠️  Partially Ready (review TODOs)";
  return "❌ Not Ready — critical information missing";
}

function unitStatusLabel(s: UnitCheckReport["unit_check_status"]): string {
  if (s === "pass") return "✅ Pass";
  if (s === "warning") return "⚠️  Warning";
  return "❌ Fail";
}

// ─── File generators ──────────────────────────────────────────────────────────

function makeReadme(input: ModelPackageInput): string {
  const {
    title, projectName, providerUsed, systemType,
    systemDescription, problemStatement,
    equations, variables, parameters, assumptionItems, limitationItems,
    report, unitReport, review,
  } = input;

  const date = new Date().toISOString().slice(0, 10);
  const paramsWithValues = parameters.filter((p) => p.value != null && String(p.value).trim() !== "").length;
  const criticals = report.missing_items.filter((m) => m.severity === "critical");
  const warnings  = report.missing_items.filter((m) => m.severity === "warning");
  const highUnits = unitReport.warnings.filter((w) => w.severity === "high").length;
  const medUnits  = unitReport.warnings.filter((w) => w.severity === "medium").length;

  const lines: string[] = [];

  lines.push(`# ${title}`);
  lines.push(`**Project:** ${projectName}`);
  lines.push(`**Generated by:** ChemAI Model Compiler  |  **Provider:** ${providerUsed}  |  **Date:** ${date}`);
  lines.push(`**Review status:** ${review?.status ?? "extracted"}`);
  if (review?.reviewer_name) lines.push(`**Reviewer:** ${review.reviewer_name}`);
  if (review?.reviewed_at) lines.push(`**Reviewed at:** ${review.reviewed_at}`);
  if (systemType) lines.push(`**System type:** ${systemType}`);
  lines.push("");

  lines.push(hr("="));
  lines.push("## Human review notes");
  lines.push(hr("="));
  lines.push("");
  lines.push(
    "Verified means manually checked by the user against the provided source, not experimentally validated.",
  );
  lines.push("");
  lines.push(`Status: ${review?.status ?? "extracted"}`);
  if (review?.review_notes) lines.push(`Notes: ${review.review_notes}`);
  if ((review?.issues_found ?? []).length > 0) {
    lines.push("Issues found:");
    for (const issue of review!.issues_found!) lines.push(`- ${issue}`);
  }
  lines.push("");

  lines.push(hr("="));
  lines.push("## What this model is");
  lines.push(hr("="));
  lines.push("");
  if (systemDescription) {
    lines.push(systemDescription);
  } else {
    lines.push("_(No system description extracted.)_");
  }
  lines.push("");

  if (problemStatement) {
    lines.push("**Problem Statement:**");
    lines.push("");
    lines.push(problemStatement);
    lines.push("");
  }

  lines.push(hr("="));
  lines.push("## What was extracted");
  lines.push(hr("="));
  lines.push("");
  lines.push(`| Item | Count | Notes |`);
  lines.push(`|---|---|---|`);
  lines.push(`| State variables | ${variables.length} | symbols with unit + role |`);
  lines.push(`| Parameters | ${parameters.length} | ${paramsWithValues} have numeric values |`);
  lines.push(`| Equations | ${equations.length} | with LaTeX + source quotes |`);
  lines.push(`| Assumptions | ${assumptionItems.length} | extracted from source text |`);
  lines.push(`| Limitations | ${limitationItems.length} | extracted from source text |`);
  lines.push("");

  lines.push(hr("="));
  lines.push("## Reproducibility assessment");
  lines.push(hr("="));
  lines.push("");
  lines.push(`**Overall score:** ${report.overall_score}/100`);
  lines.push(`**Simulation readiness:** ${readinessLabel(report.simulation_readiness)}`);
  lines.push("");
  lines.push("| Sub-score | Value |");
  lines.push("|---|---|");
  lines.push(`| Equations completeness | ${report.equations_completeness}/100 |`);
  lines.push(`| Parameters completeness | ${report.parameters_completeness}/100 |`);
  lines.push(`| Units completeness | ${report.units_completeness}/100 |`);
  lines.push(`| Initial conditions | ${report.initial_conditions_completeness}/100 |`);
  lines.push(`| Source traceability | ${report.source_traceability}/100 |`);
  lines.push("");

  lines.push(hr("="));
  lines.push("## What is missing");
  lines.push(hr("="));
  lines.push("");

  if (criticals.length === 0 && warnings.length === 0) {
    lines.push("✅ No critical gaps detected.");
  } else {
    if (criticals.length > 0) {
      lines.push("### ❌ Critical (must resolve before simulation)");
      lines.push("");
      for (const item of criticals) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
    if (warnings.length > 0) {
      lines.push("### ⚠️  Warnings (should verify)");
      lines.push("");
      for (const item of warnings) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
  }

  if (report.main_blockers.length > 0) {
    lines.push("**Simulation blockers:**");
    for (const b of report.main_blockers) {
      lines.push(`- ${b}`);
    }
    lines.push("");
  }

  lines.push(hr("="));
  lines.push("## Unit check status");
  lines.push(hr("="));
  lines.push("");
  lines.push(`**Status:** ${unitStatusLabel(unitReport.unit_check_status)}`);
  lines.push(`**Issues:** ${highUnits} high severity · ${medUnits} medium severity`);
  lines.push("");
  if (highUnits > 0) {
    lines.push("High-severity unit issues:");
    for (const w of unitReport.warnings.filter((w) => w.severity === "high")) {
      lines.push(`- ${w.message}`);
      if (w.suggestion) lines.push(`  → ${w.suggestion}`);
    }
    lines.push("");
  }

  lines.push(hr("="));
  lines.push("## How to run the Python template");
  lines.push(hr("="));
  lines.push("");
  lines.push("```bash");
  lines.push("# 1. Install dependencies");
  lines.push("pip install -r requirements.txt");
  lines.push("");
  lines.push("# 2. Open simulate.py and fill in all # TODO comments");
  lines.push("#    - Verify numeric parameter values against the source paper");
  lines.push("#    - Translate each LaTeX equation into Python (shown as comments)");
  lines.push("#    - Set realistic initial conditions for each state variable");
  lines.push("");
  lines.push("# 3. Run the simulation");
  lines.push("python simulate.py");
  lines.push("");
  lines.push("# 4. Output: model_simulation.png (time-series plot)");
  lines.push("```");
  lines.push("");
  lines.push("> **Important:** `simulate.py` is a scaffold, not a finished simulation.");
  lines.push("> All equation implementations are `# TODO` stubs — the LaTeX is shown");
  lines.push("> as a reference comment. Expert review is required before trusting output.");
  lines.push("");

  lines.push(hr("="));
  lines.push("## Files in this package");
  lines.push(hr("="));
  lines.push("");
  lines.push("| File | Description |");
  lines.push("|---|---|");
  lines.push("| `README.md` | This file |");
  lines.push("| `model_card.md` | Full human-readable model card |");
  lines.push("| `variables.csv` | Extracted state variables (symbol, unit, role) |");
  lines.push("| `parameters.csv` | Extracted parameters (symbol, value, unit, confidence) |");
  lines.push("| `equations.md` | Extracted equations with LaTeX and source quotes |");
  lines.push("| `assumptions.md` | Model assumptions from the source |");
  lines.push("| `limitations.md` | Model limitations from the source |");
  lines.push("| `missing_information.md` | Reproducibility gaps and recommended next steps |");
  lines.push("| `reproducibility_report.json` | Full reproducibility analysis (machine-readable) |");
  lines.push("| `unit_check_report.json` | Unit & dimension check results (machine-readable) |");
  lines.push("| `raw_extraction.json` | Raw extraction JSON from the provider |");
  lines.push("| `simulate.py` | Python ODE scaffold (fill in TODOs before running) |");
  lines.push("| `model_notebook.ipynb` | Jupyter notebook export (simulation workflow scaffold) |");
  lines.push("| `requirements.txt` | Python dependencies |");
  lines.push("| `source_excerpt.txt` | Source quotes from the paper used during extraction |");
  lines.push("");

  if (report.recommended_next_steps.length > 0) {
    lines.push(hr("="));
    lines.push("## Recommended next steps");
    lines.push(hr("="));
    lines.push("");
    for (let i = 0; i < report.recommended_next_steps.length; i++) {
      lines.push(`${i + 1}. ${report.recommended_next_steps[i]}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function makeModelCard(input: ModelPackageInput): string {
  const {
    title, projectName, providerUsed, domain, systemType,
    systemDescription, problemStatement,
    equations, variables, parameters, assumptionItems, limitationItems,
    raw, report, unitReport,
  } = input;

  const date = new Date().toISOString().slice(0, 10);
  const mc = raw?.model_card;
  const lines: string[] = [];

  lines.push(`# Model Card: ${title}`);
  lines.push("");
  lines.push(`| Field | Value |`);
  lines.push(`|---|---|`);
  lines.push(`| Project | ${projectName} |`);
  lines.push(`| Domain | ${domain} |`);
  if (systemType) lines.push(`| System type | ${systemType} |`);
  lines.push(`| Provider | ${providerUsed} |`);
  lines.push(`| Reproducibility | ${report.overall_score}/100 |`);
  lines.push(`| Simulation readiness | ${report.simulation_readiness} |`);
  lines.push(`| Unit check | ${unitReport.unit_check_status} |`);
  lines.push(`| Generated | ${date} |`);
  lines.push("");

  if (mc?.model_type || mc?.short_summary) {
    lines.push("## Model Summary");
    lines.push("");
    if (mc.model_type) lines.push(`**Type:** ${mc.model_type}`);
    if (mc.short_summary) lines.push(`\n${mc.short_summary}`);
    lines.push("");
    if ((mc.inputs ?? []).length > 0) lines.push(`**Inputs:** ${mc.inputs!.join(", ")}`);
    if ((mc.outputs ?? []).length > 0) lines.push(`**Outputs:** ${mc.outputs!.join(", ")}`);
    if ((mc.control_variables ?? []).length > 0) lines.push(`**Control variables:** ${mc.control_variables!.join(", ")}`);
    lines.push("");
  }

  lines.push("## System Description");
  lines.push("");
  lines.push(systemDescription || "_(not extracted)_");
  lines.push("");

  lines.push("## Problem Statement");
  lines.push("");
  lines.push(problemStatement || "_(not extracted)_");
  lines.push("");

  lines.push("## State Variables");
  lines.push("");
  if (variables.length === 0) {
    lines.push("_(none extracted)_");
  } else {
    lines.push("| Symbol | Name | Unit | Role | Source |");
    lines.push("|---|---|---|---|---|");
    for (const v of variables) {
      lines.push(`| \`${v.symbol}\` | ${safe(v.name)} | ${safe(v.unit) || "—"} | ${v.role} | ${safe(v.sourceQuote).slice(0, 80)}… |`);
    }
  }
  lines.push("");

  lines.push("## Parameters");
  lines.push("");
  if (parameters.length === 0) {
    lines.push("_(none extracted)_");
  } else {
    lines.push("| Symbol | Value | Unit | Confidence | Source |");
    lines.push("|---|---|---|---|---|");
    for (const p of parameters) {
      lines.push(`| \`${p.symbol}\` | ${safe(p.value) || "—"} | ${safe(p.unit) || "—"} | ${p.confidence} | ${safe(p.sourceQuote).slice(0, 80)}… |`);
    }
  }
  lines.push("");

  lines.push("## Equations");
  lines.push("");
  if (equations.length === 0) {
    lines.push("_(none extracted)_");
  } else {
    for (let i = 0; i < equations.length; i++) {
      const eq = equations[i];
      lines.push(`### Equation ${i + 1}: ${eq.description || "(no description)"}`);
      if (eq.latex) lines.push(`\`${eq.latex}\``);
      if (eq.sourceQuote) lines.push(`\n> ${eq.sourceQuote}`);
      lines.push("");
    }
  }

  lines.push("## Assumptions");
  lines.push("");
  if (assumptionItems.length === 0) {
    lines.push("_(none extracted)_");
  } else {
    for (const a of assumptionItems) lines.push(`- ${a.text}`);
  }
  lines.push("");

  lines.push("## Limitations");
  lines.push("");
  if (limitationItems.length === 0) {
    lines.push("_(none extracted)_");
  } else {
    for (const l of limitationItems) lines.push(`- ${l.text}`);
  }
  lines.push("");

  return lines.join("\n");
}

function makeVariablesCsv(variables: AnalysisVariable[]): string {
  const rows: string[] = [
    csvRow("symbol", "name", "unit", "role", "source_quote"),
  ];
  for (const v of variables) {
    rows.push(csvRow(v.symbol, v.name, v.unit ?? "", v.role, v.sourceQuote));
  }
  return rows.join("\n");
}

function makeParametersCsv(parameters: AnalysisParameter[]): string {
  const rows: string[] = [
    csvRow("symbol", "value", "unit", "confidence", "source_quote"),
  ];
  for (const p of parameters) {
    rows.push(csvRow(p.symbol, p.value ?? "", p.unit ?? "", p.confidence, p.sourceQuote));
  }
  return rows.join("\n");
}

function makeEquationsMd(equations: AnalysisEquation[], raw: RawExtraction | null): string {
  const rawEqs = raw?.equations ?? [];
  const lines: string[] = ["# Extracted Equations", ""];

  if (equations.length === 0 && rawEqs.length === 0) {
    lines.push("_(No equations were extracted.)_");
    return lines.join("\n");
  }

  // Prefer raw entries (richer) over normalized
  if (rawEqs.length > 0) {
    for (let i = 0; i < rawEqs.length; i++) {
      const eq = rawEqs[i];
      const label = safe(eq.label) || `Equation ${i + 1}`;
      lines.push(`## ${i + 1}. ${label}`);
      lines.push("");
      if (eq.equation_latex) {
        lines.push("**LaTeX:**");
        lines.push("```");
        lines.push(eq.equation_latex);
        lines.push("```");
      }
      if (eq.equation_plaintext && eq.equation_plaintext !== eq.equation_latex) {
        lines.push(`**Plain text:** ${eq.equation_plaintext}`);
      }
      if (eq.meaning) lines.push(`**Meaning:** ${eq.meaning}`);
      if ((eq.variables_involved ?? []).length > 0) {
        lines.push(`**Symbols involved:** ${eq.variables_involved!.join(", ")}`);
      }
      if (eq.confidence) lines.push(`**Confidence:** ${eq.confidence}`);
      if (eq.source_context) {
        lines.push("");
        lines.push(`> ${eq.source_context}`);
      }
      lines.push("");
    }
  } else {
    for (let i = 0; i < equations.length; i++) {
      const eq = equations[i];
      lines.push(`## ${i + 1}. ${eq.description || "(no description)"}`);
      lines.push("");
      if (eq.latex) {
        lines.push("```");
        lines.push(eq.latex);
        lines.push("```");
      }
      if (eq.sourceQuote) {
        lines.push("");
        lines.push(`> ${eq.sourceQuote}`);
      }
      lines.push("");
    }
  }

  return lines.join("\n");
}

function makeAssumptionsMd(items: AnalysisAssumption[]): string {
  const lines: string[] = ["# Model Assumptions", ""];
  if (items.length === 0) {
    lines.push("_(No assumptions were extracted.)_");
  } else {
    for (let i = 0; i < items.length; i++) {
      lines.push(`${i + 1}. ${items[i].text}`);
    }
  }
  return lines.join("\n");
}

function makeLimitationsMd(items: AnalysisAssumption[]): string {
  const lines: string[] = ["# Model Limitations", ""];
  if (items.length === 0) {
    lines.push("_(No limitations were extracted.)_");
  } else {
    for (let i = 0; i < items.length; i++) {
      lines.push(`${i + 1}. ${items[i].text}`);
    }
  }
  return lines.join("\n");
}

function makeMissingInfoMd(report: ReproducibilityReport): string {
  const lines: string[] = ["# Missing Information Report", ""];
  lines.push(`_Generated by ChemAI Model Compiler reproducibility engine — ${new Date().toISOString().slice(0, 10)}_`);
  lines.push("");
  lines.push(`**Overall reproducibility score:** ${report.overall_score}/100`);
  lines.push(`**Simulation readiness:** ${report.simulation_readiness}`);
  lines.push("");

  const criticals = report.missing_items.filter((m) => m.severity === "critical");
  const warnings  = report.missing_items.filter((m) => m.severity === "warning");
  const infos     = report.missing_items.filter((m) => m.severity === "info");

  if (criticals.length === 0 && warnings.length === 0 && infos.length === 0) {
    lines.push("✅ No issues detected.");
  } else {
    if (criticals.length > 0) {
      lines.push("## ❌ Critical Issues");
      lines.push("_Must resolve before attempting simulation._");
      lines.push("");
      for (const item of criticals) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
    if (warnings.length > 0) {
      lines.push("## ⚠️  Warnings");
      lines.push("_Should verify before trusting simulation output._");
      lines.push("");
      for (const item of warnings) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
    if (infos.length > 0) {
      lines.push("## ℹ️  Informational");
      lines.push("");
      for (const item of infos) {
        lines.push(`- **[${item.category}]** ${item.description}`);
      }
      lines.push("");
    }
  }

  if (report.main_blockers.length > 0) {
    lines.push("## Simulation Blockers");
    lines.push("");
    for (const b of report.main_blockers) lines.push(`- ${b}`);
    lines.push("");
  }

  if (report.recommended_next_steps.length > 0) {
    lines.push("## Recommended Next Steps");
    lines.push("");
    for (let i = 0; i < report.recommended_next_steps.length; i++) {
      lines.push(`${i + 1}. ${report.recommended_next_steps[i]}`);
    }
    lines.push("");
  }

  return lines.join("\n");
}

function makeRequirementsTxt(): string {
  return [
    "# Python dependencies for ChemAI Model Compiler simulation template",
    "# Install with: pip install -r requirements.txt",
    "",
    "numpy>=1.24",
    "scipy>=1.10",
    "matplotlib>=3.7",
    "",
  ].join("\n");
}

function makeSourceExcerpt(
  equations: AnalysisEquation[],
  variables: AnalysisVariable[],
  parameters: AnalysisParameter[],
  raw: RawExtraction | null
): string {
  const lines: string[] = [
    "Source Quotes Extracted from the Paper",
    "=" .repeat(60),
    "Generated by ChemAI Model Compiler — these are verbatim excerpts used",
    "to extract model data. They serve as the traceability record.",
    "",
  ];

  const seen = new Set<string>();
  function addQuote(category: string, symbol: string, quote: string) {
    const q = quote.trim();
    if (!q || seen.has(q)) return;
    seen.add(q);
    lines.push(`[${category}] ${symbol}`);
    lines.push(hr("-", 40));
    lines.push(q);
    lines.push("");
  }

  lines.push("EQUATIONS");
  lines.push(hr("=", 40));
  lines.push("");
  for (const eq of equations) {
    addQuote("Equation", eq.description || eq.latex.slice(0, 40), eq.sourceQuote);
  }
  // Also check raw equations for source_context
  for (const eq of raw?.equations ?? []) {
    if (eq.source_context) {
      addQuote("Equation (raw)", safe(eq.label) || safe(eq.equation_latex).slice(0, 40), eq.source_context);
    }
  }

  lines.push("VARIABLES");
  lines.push(hr("=", 40));
  lines.push("");
  for (const v of variables) {
    addQuote("Variable", v.symbol, v.sourceQuote);
  }
  for (const v of raw?.state_variables ?? []) {
    if (v.source_context) {
      addQuote("Variable (raw)", safe(v.symbol), v.source_context);
    }
  }

  lines.push("PARAMETERS");
  lines.push(hr("=", 40));
  lines.push("");
  for (const p of parameters) {
    addQuote("Parameter", p.symbol, p.sourceQuote);
  }
  for (const p of raw?.parameters ?? []) {
    if (p.source_context) {
      addQuote("Parameter (raw)", safe(p.symbol), p.source_context);
    }
  }

  if (seen.size === 0) {
    lines.push("(No source quotes were extracted for this model.)");
  }

  return lines.join("\n");
}

// ─── Main entry point ─────────────────────────────────────────────────────────

/**
 * Generate all files for the model package.
 * Returns a flat Record<filename, content> — the caller wraps these in a ZIP.
 */
export function generateModelPackage(
  input: ModelPackageInput
): Record<string, string> {
  const { equations, variables, parameters, assumptionItems, limitationItems, raw, report, unitReport, pythonCode } = input;

  const files: Record<string, string> = {};

  files["README.md"]                   = makeReadme(input);
  files["model_card.md"]               = makeModelCard(input);
  files["variables.csv"]               = makeVariablesCsv(variables);
  files["parameters.csv"]              = makeParametersCsv(parameters);
  files["equations.md"]                = makeEquationsMd(equations, raw);
  files["assumptions.md"]              = makeAssumptionsMd(assumptionItems);
  files["limitations.md"]              = makeLimitationsMd(limitationItems);
  files["missing_information.md"]      = makeMissingInfoMd(report);
  files["reproducibility_report.json"] = JSON.stringify(report, null, 2);
  files["unit_check_report.json"]      = JSON.stringify(unitReport, null, 2);
  files["raw_extraction.json"]         = raw != null
    ? JSON.stringify(raw, null, 2)
    : '{\n  "_note": "No raw extraction JSON available for this record."\n}';
  files["simulate.py"]                 = pythonCode;
  files["model_notebook.ipynb"]        = generateJupyterNotebook({
    title: input.title,
    projectName: input.projectName,
    providerUsed: input.providerUsed,
    systemType: input.systemType,
    systemDescription: input.systemDescription ?? null,
    equations,
    variables,
    parameters,
    assumptions: [...assumptionItems, ...limitationItems],
    raw,
    report,
    unitReport,
    pythonCode,
  });
  files["requirements.txt"]            = makeRequirementsTxt();
  files["source_excerpt.txt"]          = makeSourceExcerpt(equations, variables, parameters, raw);

  return files;
}
